server:
  port: 8081

spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:9999 # server from were to get the rest of configuration

  h2:
    console:
      enabled: true

