server:
  port: 8081

spring:
  application:
    name: customer-service

  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:customer-db
  h2:
    console:
      enabled: true

