server:
  port: 8082

spring:
  application:
    name: account-service

  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:account-db
  h2:
    console:
      enabled: true

